/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_Linux */

#ifndef _Included_name_pachler_nio_file_impl_Linux
#define _Included_name_pachler_nio_file_impl_Linux
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: EINTR */
/* Inaccessible static: EINVAL */
/* Inaccessible static: EBADF */
/* Inaccessible static: ENOENT */
/* Inaccessible static: O_RDONLY */
/* Inaccessible static: O_WRONLY */
/* Inaccessible static: O_RDWR */
/* Inaccessible static: O_APPEND */
/* Inaccessible static: O_CREAT */
/* Inaccessible static: O_EXCL */
/* Inaccessible static: O_NOCTTY */
/* Inaccessible static: O_NONBLOCK */
/* Inaccessible static: O_SYNC */
/* Inaccessible static: O_TRUNC */
/* Inaccessible static: S_ISUID */
/* Inaccessible static: S_ISGID */
/* Inaccessible static: S_IRWXU */
/* Inaccessible static: S_IRUSR */
/* Inaccessible static: S_IWUSR */
/* Inaccessible static: S_IXUSR */
/* Inaccessible static: S_IRWXG */
/* Inaccessible static: S_IRGRP */
/* Inaccessible static: S_IWGRP */
/* Inaccessible static: S_IXGRP */
/* Inaccessible static: S_IRWXO */
/* Inaccessible static: S_IROTH */
/* Inaccessible static: S_IWOTH */
/* Inaccessible static: S_IXOTH */
#undef name_pachler_nio_file_impl_Linux_IN_ACCESS
#define name_pachler_nio_file_impl_Linux_IN_ACCESS 1L
#undef name_pachler_nio_file_impl_Linux_IN_MODIFY
#define name_pachler_nio_file_impl_Linux_IN_MODIFY 2L
#undef name_pachler_nio_file_impl_Linux_IN_ATTRIB
#define name_pachler_nio_file_impl_Linux_IN_ATTRIB 4L
#undef name_pachler_nio_file_impl_Linux_IN_CLOSE_WRITE
#define name_pachler_nio_file_impl_Linux_IN_CLOSE_WRITE 8L
#undef name_pachler_nio_file_impl_Linux_IN_CLOSE_NOWRITE
#define name_pachler_nio_file_impl_Linux_IN_CLOSE_NOWRITE 16L
#undef name_pachler_nio_file_impl_Linux_IN_CLOSE
#define name_pachler_nio_file_impl_Linux_IN_CLOSE 24L
#undef name_pachler_nio_file_impl_Linux_IN_OPEN
#define name_pachler_nio_file_impl_Linux_IN_OPEN 32L
#undef name_pachler_nio_file_impl_Linux_IN_MOVED_FROM
#define name_pachler_nio_file_impl_Linux_IN_MOVED_FROM 64L
#undef name_pachler_nio_file_impl_Linux_IN_MOVED_TO
#define name_pachler_nio_file_impl_Linux_IN_MOVED_TO 128L
#undef name_pachler_nio_file_impl_Linux_IN_MOVE
#define name_pachler_nio_file_impl_Linux_IN_MOVE 192L
#undef name_pachler_nio_file_impl_Linux_IN_CREATE
#define name_pachler_nio_file_impl_Linux_IN_CREATE 256L
#undef name_pachler_nio_file_impl_Linux_IN_DELETE
#define name_pachler_nio_file_impl_Linux_IN_DELETE 512L
#undef name_pachler_nio_file_impl_Linux_IN_DELETE_SELF
#define name_pachler_nio_file_impl_Linux_IN_DELETE_SELF 1024L
#undef name_pachler_nio_file_impl_Linux_IN_MOVE_SELF
#define name_pachler_nio_file_impl_Linux_IN_MOVE_SELF 2048L
#undef name_pachler_nio_file_impl_Linux_IN_UNMOUNT
#define name_pachler_nio_file_impl_Linux_IN_UNMOUNT 8192L
#undef name_pachler_nio_file_impl_Linux_IN_Q_OVERFLOW
#define name_pachler_nio_file_impl_Linux_IN_Q_OVERFLOW 16384L
#undef name_pachler_nio_file_impl_Linux_IN_IGNORED
#define name_pachler_nio_file_impl_Linux_IN_IGNORED 32768L
#undef name_pachler_nio_file_impl_Linux_IN_ONLYDIR
#define name_pachler_nio_file_impl_Linux_IN_ONLYDIR 16777216L
#undef name_pachler_nio_file_impl_Linux_IN_DONT_FOLLOW
#define name_pachler_nio_file_impl_Linux_IN_DONT_FOLLOW 33554432L
#undef name_pachler_nio_file_impl_Linux_IN_MASK_ADD
#define name_pachler_nio_file_impl_Linux_IN_MASK_ADD 536870912L
#undef name_pachler_nio_file_impl_Linux_IN_ISDIR
#define name_pachler_nio_file_impl_Linux_IN_ISDIR 1073741824L
#undef name_pachler_nio_file_impl_Linux_IN_ONESHOT
#define name_pachler_nio_file_impl_Linux_IN_ONESHOT -2147483648L
#undef name_pachler_nio_file_impl_Linux_IN_ALL_EVENTS
#define name_pachler_nio_file_impl_Linux_IN_ALL_EVENTS 4095L
#undef name_pachler_nio_file_impl_Linux_NFS_SUPER_MAGIC
#define name_pachler_nio_file_impl_Linux_NFS_SUPER_MAGIC 26985L
#undef name_pachler_nio_file_impl_Linux_SMB_SUPER_MAGIC
#define name_pachler_nio_file_impl_Linux_SMB_SUPER_MAGIC 20859L
/*
 * Class:     name_pachler_nio_file_impl_Linux
 * Method:    inotify_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_Linux_inotify_1init
  (JNIEnv *, jclass);

/*
 * Class:     name_pachler_nio_file_impl_Linux
 * Method:    inotify_add_watch
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_Linux_inotify_1add_1watch
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     name_pachler_nio_file_impl_Linux
 * Method:    inotify_rm_watch
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_Linux_inotify_1rm_1watch
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     name_pachler_nio_file_impl_Linux
 * Method:    statfs
 * Signature: (Ljava/lang/String;Lname/pachler/nio/file/impl/Linux$statfs;)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_Linux_statfs
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
