/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_WindowsPathWatchService_ByteBuffer */

#ifndef _Included_name_pachler_nio_file_impl_WindowsPathWatchService_ByteBuffer
#define _Included_name_pachler_nio_file_impl_WindowsPathWatchService_ByteBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_pachler_nio_file_impl_WindowsPathWatchService_ByteBuffer
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_WindowsPathWatchService_00024ByteBuffer_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     name_pachler_nio_file_impl_WindowsPathWatchService_ByteBuffer
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_WindowsPathWatchService_00024ByteBuffer_deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     name_pachler_nio_file_impl_WindowsPathWatchService_ByteBuffer
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_WindowsPathWatchService_00024ByteBuffer_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
