/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_Unix_timespec */

#ifndef _Included_name_pachler_nio_file_impl_Unix_timespec
#define _Included_name_pachler_nio_file_impl_Unix_timespec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_initNative
  (JNIEnv *, jclass);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    createPeer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_createPeer
  (JNIEnv *, jclass);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    destroyPeer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_destroyPeer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    get_tv_sec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_get_1tv_1sec
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    get_tv_nsec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_get_1tv_1nsec
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    set_tv_sec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_set_1tv_1sec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    set_tv_nsec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_set_1tv_1nsec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     name_pachler_nio_file_impl_Unix_timespec
 * Method:    set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_Unix_00024timespec_set
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
