/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_BSD */

#ifndef _Included_name_pachler_nio_file_impl_BSD
#define _Included_name_pachler_nio_file_impl_BSD
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: EINTR */
/* Inaccessible static: EINVAL */
/* Inaccessible static: EBADF */
/* Inaccessible static: ENOENT */
/* Inaccessible static: O_RDONLY */
/* Inaccessible static: O_WRONLY */
/* Inaccessible static: O_RDWR */
/* Inaccessible static: O_APPEND */
/* Inaccessible static: O_CREAT */
/* Inaccessible static: O_EXCL */
/* Inaccessible static: O_NOCTTY */
/* Inaccessible static: O_NONBLOCK */
/* Inaccessible static: O_SYNC */
/* Inaccessible static: O_TRUNC */
/* Inaccessible static: S_ISUID */
/* Inaccessible static: S_ISGID */
/* Inaccessible static: S_IRWXU */
/* Inaccessible static: S_IRUSR */
/* Inaccessible static: S_IWUSR */
/* Inaccessible static: S_IXUSR */
/* Inaccessible static: S_IRWXG */
/* Inaccessible static: S_IRGRP */
/* Inaccessible static: S_IWGRP */
/* Inaccessible static: S_IXGRP */
/* Inaccessible static: S_IRWXO */
/* Inaccessible static: S_IROTH */
/* Inaccessible static: S_IWOTH */
/* Inaccessible static: S_IXOTH */
/* Inaccessible static: EV_ADD */
/* Inaccessible static: EV_ENABLE */
/* Inaccessible static: EV_DISABLE */
/* Inaccessible static: EV_DELETE */
/* Inaccessible static: EV_ONESHOT */
/* Inaccessible static: EV_CLEAR */
/* Inaccessible static: EV_EOF */
/* Inaccessible static: EV_ERROR */
/* Inaccessible static: EVFILT_VNODE */
/* Inaccessible static: EVFILT_PROC */
/* Inaccessible static: NOTE_DELETE */
/* Inaccessible static: NOTE_WRITE */
/* Inaccessible static: NOTE_EXTEND */
/* Inaccessible static: NOTE_ATTRIB */
/* Inaccessible static: NOTE_LINK */
/* Inaccessible static: NOTE_RENAME */
/* Inaccessible static: NOTE_REVOKE */
/* Inaccessible static: NOTE_EXIT */
/* Inaccessible static: NOTE_FORK */
/* Inaccessible static: NOTE_EXEC */
/* Inaccessible static: NOTE_TRACK */
/* Inaccessible static: NOTE_TRACKERR */
/*
 * Class:     name_pachler_nio_file_impl_BSD
 * Method:    kqueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_BSD_kqueue
  (JNIEnv *, jclass);

/*
 * Class:     name_pachler_nio_file_impl_BSD
 * Method:    kevent
 * Signature: (I[Lname/pachler/nio/file/impl/BSD$kevent;[Lname/pachler/nio/file/impl/BSD$kevent;Lname/pachler/nio/file/impl/Unix$timespec;)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_BSD_kevent
  (JNIEnv *, jclass, jint, jobjectArray, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
