/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_BSD_kevent */

#ifndef _Included_name_pachler_nio_file_impl_BSD_kevent
#define _Included_name_pachler_nio_file_impl_BSD_kevent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_initNative
  (JNIEnv *, jclass);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    createPeer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_createPeer
  (JNIEnv *, jclass);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    destroyPeer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_destroyPeer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    get_ident
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_get_1ident
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    set_ident
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_set_1ident
  (JNIEnv *, jobject, jlong);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    get_filter
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_get_1filter
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    set_filter
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_set_1filter
  (JNIEnv *, jobject, jshort);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    get_flags
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_get_1flags
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    set_flags
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_set_1flags
  (JNIEnv *, jobject, jshort);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    get_fflags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_get_1fflags
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    set_fflags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_set_1fflags
  (JNIEnv *, jobject, jint);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    get_data
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_get_1data
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    set_data
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_set_1data
  (JNIEnv *, jobject, jlong);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    get_udata
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_get_1udata
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_BSD_kevent
 * Method:    set_udata
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_BSD_00024kevent_set_1udata
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
