/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_BSD_kevent_IntStringMapping */

#ifndef _Included_name_pachler_nio_file_impl_BSD_kevent_IntStringMapping
#define _Included_name_pachler_nio_file_impl_BSD_kevent_IntStringMapping
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
