/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_NativePathWatchService */

#ifndef _Included_name_pachler_nio_file_impl_NativePathWatchService
#define _Included_name_pachler_nio_file_impl_NativePathWatchService
#ifdef __cplusplus
extern "C" {
#endif
#undef name_pachler_nio_file_impl_NativePathWatchService_OVERFLOW
#define name_pachler_nio_file_impl_NativePathWatchService_OVERFLOW 1L
#undef name_pachler_nio_file_impl_NativePathWatchService_CREATED
#define name_pachler_nio_file_impl_NativePathWatchService_CREATED 2L
#undef name_pachler_nio_file_impl_NativePathWatchService_DELETED
#define name_pachler_nio_file_impl_NativePathWatchService_DELETED 4L
#undef name_pachler_nio_file_impl_NativePathWatchService_MODIFIED
#define name_pachler_nio_file_impl_NativePathWatchService_MODIFIED 8L
#undef name_pachler_nio_file_impl_NativePathWatchService_QUEUELENGTH
#define name_pachler_nio_file_impl_NativePathWatchService_QUEUELENGTH 4096L
/*
 * Class:     name_pachler_nio_file_impl_NativePathWatchService
 * Method:    openImpl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_name_pachler_nio_file_impl_NativePathWatchService_openImpl
  (JNIEnv *, jobject);

/*
 * Class:     name_pachler_nio_file_impl_NativePathWatchService
 * Method:    closeImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_NativePathWatchService_closeImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     name_pachler_nio_file_impl_NativePathWatchService
 * Method:    activateImpl
 * Signature: (JLname/pachler/nio/file/impl/PathWatchKey;Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_NativePathWatchService_activateImpl
  (JNIEnv *, jobject, jlong, jobject, jstring, jint, jboolean);

/*
 * Class:     name_pachler_nio_file_impl_NativePathWatchService
 * Method:    deactivateImpl
 * Signature: (JLname/pachler/nio/file/impl/PathWatchKey;)V
 */
JNIEXPORT void JNICALL Java_name_pachler_nio_file_impl_NativePathWatchService_deactivateImpl
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
