/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_Windows_SECURITY_DESCRIPTOR */

#ifndef _Included_name_pachler_nio_file_impl_Windows_SECURITY_DESCRIPTOR
#define _Included_name_pachler_nio_file_impl_Windows_SECURITY_DESCRIPTOR
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
