/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_Unix_dirent */

#ifndef _Included_name_pachler_nio_file_impl_Unix_dirent
#define _Included_name_pachler_nio_file_impl_Unix_dirent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
