/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_pachler_nio_file_impl_UnixPathWatchService */

#ifndef _Included_name_pachler_nio_file_impl_UnixPathWatchService
#define _Included_name_pachler_nio_file_impl_UnixPathWatchService
#ifdef __cplusplus
extern "C" {
#endif
#undef name_pachler_nio_file_impl_UnixPathWatchService_FLAG_WATCH_SUBTREE
#define name_pachler_nio_file_impl_UnixPathWatchService_FLAG_WATCH_SUBTREE 4096L
#undef name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_RENAME_FROM
#define name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_RENAME_FROM 2L
#undef name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_RENAME_TO
#define name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_RENAME_TO 4L
#undef name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_CREATE
#define name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_CREATE 8L
#undef name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_DELETE
#define name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_DELETE 16L
#undef name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_MODIFY
#define name_pachler_nio_file_impl_UnixPathWatchService_FLAG_FILTER_ENTRY_MODIFY 32L
#undef name_pachler_nio_file_impl_UnixPathWatchService_EINTR
#define name_pachler_nio_file_impl_UnixPathWatchService_EINTR 4L
/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    select
 * Signature: ([I[I[IJ)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_select
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jlong);

/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    ioctl_FIONREAD
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_ioctl_1FIONREAD
  (JNIEnv *, jclass, jint);

/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    read
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_read
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    write
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_write
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    pipe
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_pipe
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     name_pachler_nio_file_impl_UnixPathWatchService
 * Method:    errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_name_pachler_nio_file_impl_UnixPathWatchService_errno
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
